### ISSUE TITLE
Example on how to use

### ISSUE THREAD

**Issue by macbruker** [mintbridge/metalsmith-include-content#2]
I would love to see an example on how to use this.

**Comment by mintbridge** [comment]
hi, i've added an example of how to use it in markdown to the readme, does that help?

**Comment by stavros-liaskos** [comment]
Would it be possible to have a more detailed example? What about relative paths? Can I include other type of files and have a link with their name?

**Comment by mintbridge** [comment]
Hi, relative paths wont work as it needs to be file from the metalsmith list of files. Any file that is in the list should work, but i'm not sure what you mean by link with their name? This will pull the content in from the file and display it inline

**Comment by stavros-liaskos** [comment]
I wasn't sure this plugin does what I need so yesterday I found a workaround using another plugin.
http://stackoverflow.com/questions/40364880/register-custom-handlebar-helper-in-metalsmith

**Comment by mintbridge** [comment]
ah ok, yeah so that one would create a link, this pulls the content form the path into the current file
